version: '3.8'

services:
  # 1. MQTT Broker (SSL Enabled)
  broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ../broker/config/mosquitto.secure.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/certs
    restart: unless-stopped

  # 2. Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: iot_data
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    restart: unless-stopped

  # 3. Backend Sink (Core Logic)
  sink:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file: .env.dev
    volumes:
      - ../backend:/app/backend:ro
      - ./certs:/app/certs:ro
      - ./data/mqtt_store:/app/mqtt_store
    depends_on:
      - broker
      - db
    restart: always

  # 4. Web Gateway
  web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    env_file: .env.dev
    ports:
      - "5000:5000"
    volumes:
      - ../web:/app/web:ro
      - ./data/mqtt_store:/mqtt_store:ro
    depends_on:
      - sink
    restart: always

volumes:
  db_data_dev:
